# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "docker-host"
  config.vm.provision "docker"
  config.vm.define config.vm.hostname

  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 5601, host: 5601

  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
  end

  config.vm.synced_folder 'esdata', '/esdata', create: true
end
